AllCops:
  Exclude:
    - "app/mailers/application_mailer.rb"
    - "bin/**/*"
    - "config/**/*"
    - "config.ru"
    - "db/**/*"
    - "node_modules/**/*"
    - "Rakefile"
    - "test/test_helper.rb"
Lint/AmbiguousOperator:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Metrics/LineLength:
  Max: 120
Rails:
  Enabled: true
Rails/Delegate:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Alias:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*"
Style/ClassCheck:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/MethodName:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "Gemfile"
Style/TrailingWhitespace:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false

