default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ankran-nembo_development

test:
  <<: *default
  database: ankran-nembo_test

production:
  <<: *default
  database: ankran-nembo_production
  username: ankran-nembo
  password: <%= ENV['ANKRAN-NEMBO_DATABASE_PASSWORD'] %>
